version: '3.8'

services:
  blog-server:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    image: blog-server-dev:latest
    container_name: blog-server-dev
    ports:
      - "8080:8000"
    restart: unless-stopped
    volumes:
      - ./web-server:/app
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge